artifacts_root: artifacts



data_ingestion: #always make sure for the indentations otherwise it will give an error.
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/ravina029/datasets/raw/main/WineQT.csv.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: /Users/ravina/Desktop/project_mlflow/artifacts/data_ingestion/WineQT.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: /Users/ravina/Desktop/project_mlflow/artifacts/data_ingestion/WineQT.csv  


model_trainer: 
  root_dir: artifacts/model_trainer
  train_data_path: /Users/ravina/Desktop/project_mlflow/artifacts/data_transformation/train.csv
  test_data_path: /Users/ravina/Desktop/project_mlflow/artifacts/data_transformation/test.csv
  model_name: model.joblib







